[connections]
neo4j_uri = neo4j+s://658ecbb9.databases.neo4j.io
neo4j_user = neo4j
neo4j_password = fnP8gdAU3XfuItnVcpZsmvQ1WPac8Fm4aruFf7VoN3o

#git add .gitignore
#git commit -m "Ignore secrets.toml in future commits"
#git push origin main

