[connections]
neo4j_uri = "bolt+s://your-instance.databases.neo4j.io"
neo4j_user = "neo4j"
neo4j_password = "your-password"

git add .gitignore
git commit -m "Ignore secrets.toml in future commits"
git push origin main

